sonar.projectKey=T8_Jose_Huaman
sonar.sources=.
sonar.exclusions=node_modules/**, coverage/**, **/*.test.js
sonar.tests=.
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=consumer.js, rabbitmq.js, .github/**